- name: Install and configure default packages for ubuntu machines
  hosts: all
  become: yes
  roles:
    - python
    - git
    - tmux
    - vim
    - node


- name: Install and configure DNS server using dnsmasq
  hosts: dnsserver
  become: yes
  roles:
    - dnsmasq