- name: Install and configure default packages for ubuntu machines
  hosts: all
  become: yes
  roles:
    - python
    - git
    - tmux
    - vim
    - node
    - julian-setup
    # - ssh enable at startup
  tags:
    - none
    - linux-config
    - docker-config

- name: Install and configure DNS server using dnsmasq
  hosts: dnsserver
  become: yes
  roles:
    - dnsmasq
  tags:
    - none
    - dns-config

- name: Install Docker
  hosts: all
  become: yes  
  roles:
    - docker
  tags:
    - none
    - docker-config

# - name: Configure laptop
#   hosts: all
#   become: yes
#   roles:
#     - laptop
#   tags:
#     - none
#     - laptop-config
#     - docker-config