---
- name: Install tmux Package
  apt:
    name: tmux
    state: latest
- name: Place tmux config in home dir
  command: "cp {{ role_path  }}/files/tmux.conf ~/.tmux.conf"

- name: Set permissions on tmux config
  file:
    path: ~/.tmux.conf
    owner: atjulian
    group: atjulian
    mode: 0644

- name: Remove executable attribute on tmux conf
  command: chmod -x+X ~/.tmux.conf
  warn: false
