---
- name: Install tmux Package
  apt:
    name: tmux
    state: latest

- name: Place tmux config in home dir
  become: false
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Set permissions on tmux config
  become: false
  file:
    path: ~/.tmux.conf
    owner: "{{ unix_user }}"
    group: "{{ unix_user }}"
    mode: '0644'

- name: Remove executable attribute on tmux conf
  command: chmod -x+X ~/.tmux.conf
  args:
    warn: false
