---
- name: Install tmux Package
  apt:
    name: tmux
    state: latest
- name: Place tmux config in home dir
  copy:
    src: ../../../config/.tmux.conf
    dest: ~/
    owner: atjulian
    group: atjulian
    mode: '0644'
